version: '3.3'

volumes:
  static_value:
  media_value:
  postgres_data_catalog:

services:
  database:
    image: postgres:13.3
    container_name: database
    volumes:
      - postgres_data_catalog:/var/lib/postgresql/data/
    environment:
      - DB_NAME=django
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - DB_HOST=django
      - DB_PORT=5432

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
#    command: cp -r /app/ /result_build
    volumes:
      - ../frontend/:/app/result_build/

  be_catalog:
    build: ../lib_catalog/.
    container_name: be_catalog
    restart: always
    ports:
    - 8000:8000
    volumes:
      - static_value:/code/static/
#      - media_value:/code/media/
    depends_on:
      - database

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - be_catalog
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../frontend/build:/usr/share/nginx/html/
#      - media_value:/usr/share/nginx/html/media
#      - static_value:/usr/share/nginx/html/static
